# Generated by Django 6.0.4 on 2026-04-25 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organization_partner_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bulkrmaupload',
            name='invalid_row_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkrmaupload',
            name='jobs_created_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bulkrmaupload',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulkrmaupload',
            name='row_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bulkrmaupload',
            name='valid_row_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='B2B owner; consumer jobs leave null.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_jobs', to='core.organization'),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='partner_reference',
            field=models.CharField(blank=True, help_text="Partner's own reference / RMA line id from bulk upload.", max_length=128),
        ),
        migrations.AddIndex(
            model_name='repairjob',
            index=models.Index(fields=['organization', '-created_at'], name='core_repair_organiz_e4734e_idx'),
        ),
        migrations.AddField(
            model_name='partnerinvite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerinvite',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.organization'),
        ),
        migrations.AddIndex(
            model_name='partnerinvite',
            index=models.Index(fields=['token'], name='core_partne_token_7225c4_idx'),
        ),
    ]
