# Generated by Django 6.0.4 on 2026-04-25 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_partner_b2b_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairFaultCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RepairIssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Repair issue categories',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='repairjob',
            name='booking_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Structured consumer intake for Vision / ERP (schema_version, device, issue, customer, etc.).'),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='imei',
            field=models.CharField(blank=True, help_text='15-digit IMEI when supplied on consumer booking.', max_length=32),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='issue_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='quote_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='shipping_country',
            field=models.CharField(default='ZA', max_length=2),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='shipping_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='shipping_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='shipping_province',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='warranty_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='issue_fault_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_jobs', to='core.repairfaultcode'),
        ),
        migrations.AddField(
            model_name='repairfaultcode',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_codes', to='core.repairissuecategory'),
        ),
        migrations.AddField(
            model_name='repairjob',
            name='issue_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_jobs', to='core.repairissuecategory'),
        ),
        migrations.AddConstraint(
            model_name='repairfaultcode',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='repair_fault_category_code_uniq'),
        ),
    ]
