# Generated by Django 6.0.4 on 2026-04-25 15:16

from django.db import migrations, models


def forwards_fix_consumer_intake_status(apps, schema_editor):
    """Older web bookings used `received` before `intake_submitted` existed."""
    RepairJob = apps.get_model("core", "RepairJob")
    RepairJob.objects.filter(
        status="received",
        organization_id__isnull=True,
        issue_category_id__isnull=False,
    ).update(status="intake_submitted")


def backwards_noop(apps, schema_editor):
    RepairJob = apps.get_model("core", "RepairJob")
    RepairJob.objects.filter(status="intake_submitted").update(status="received")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_issue_and_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairjob',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('intake_submitted', 'Booking confirmed — awaiting your device'), ('received', 'Device received at workshop'), ('under_assessment', 'Under assessment'), ('repair_in_progress', 'Repair in progress'), ('awaiting_parts', 'Awaiting parts'), ('completed', 'Completed'), ('ready_for_return', 'Ready for return')], default='draft', max_length=32),
        ),
        migrations.RunPython(forwards_fix_consumer_intake_status, backwards_noop),
    ]
