# Generated by Django 6.0.4 on 2026-04-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_intake_submitted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairjob',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('intake_submitted', 'Booking confirmed — awaiting your device'), ('received', 'Received'), ('under_assessment', 'Under assessment'), ('repair_in_progress', 'Repair in progress'), ('awaiting_parts', 'Awaiting parts'), ('completed', 'Completed'), ('ready_for_return', 'Ready for return')], default='draft', max_length=32),
        ),
    ]
