# Generated by Django 6.0.4 on 2026-04-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_repair_job_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='lead_type',
            field=models.CharField(blank=True, help_text='Segment / role (dropdown).', max_length=128),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='region',
            field=models.CharField(blank=True, help_text='Province / state.', max_length=120),
        ),
    ]
